ScalaCodeSnippet1.scala

in intellij:
  import the scala extension
  either press the run button in the IDE and run through IDEA or in the sbt shell press the run command
  
For the scala files in the SecondCodeSnippet

in intellij:
  import the scala extension
  either press the run button in the IDE and run through IDEA or in the sbt shell press the run command
